name: pehlivan_isg
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  url_launcher: ^6.3.0

  # --- GÜVENLİK PAKETLERİ ---
  local_auth: ^2.3.0
  flutter_secure_storage: ^9.2.2

  # --- AÇILIŞ EKRANI ---
  flutter_native_splash: ^2.4.0

  # --- UYGULAMA PAKETLERİ ---
  flutter_dotenv: ^5.2.1
  pdf: ^3.11.1
  printing: ^5.13.1
  path_provider: ^2.1.4
  share_plus: ^10.0.0
  http: ^1.6.0
  google_generative_ai: any
  sqflite: ^2.3.3+1
  path: ^1.9.0
  file_picker: ^8.1.2

# ---------------------------------------------------------
# FLUTTER AYARLARI VE ASSET TANIMLAMALARI
# ---------------------------------------------------------
flutter:
  uses-material-design: true
  assets:
    - assets/
    - .env

# ---------------------------------------------------------
# UYGULAMA İKONU AYARLARI
# ---------------------------------------------------------
flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/yeni_ikon.png"
  adaptive_icon_background: "#0d1117"
  adaptive_icon_foreground: "assets/yeni_ikon.png"

flutter_native_splash:
  color: "#0d1117"
  image: assets/splash_logo.png
  android_gravity: center
  fullscreen: false

  android_12:
    image: assets/splash_logo.png
    color: "#0d1117"